#!/usr/bin/env python3
"""Generate lightweight ORM helpers from SQL annotations via libclang.

Example:
  ./scripts/sql_orm_codegen.py \
    --input include/app/models.h \
    --output include/app/models_orm.gen.h \
    --clang-arg=-Iinclude
"""

from __future__ import annotations

import argparse
import dataclasses
import pathlib
import re
import sys

try:
    from clang import cindex
except ImportError as exc:  # pragma: no cover
    raise SystemExit(
        "error: python package 'clang' is required (pip install clang)"
    ) from exc


ANNOTATE_PREFIX_TABLE = "table:"
ANNOTATE_PREFIX_COLUMN = "col:"


@dataclasses.dataclass
class FieldDef:
    member: str
    column: str
    primary_key: bool
    annotated: bool = False


@dataclasses.dataclass
class ModelDef:
    cpp_type: str
    local_name: str
    table: str
    fields: list[FieldDef]


def snake_case(name: str) -> str:
    s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    s2 = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1)
    return s2.replace("__", "_").strip("_").lower()


def escape_cpp_string(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def cursor_annotations(cursor: cindex.Cursor) -> list[str]:
    out: list[str] = []
    for child in cursor.get_children():
        if child.kind == cindex.CursorKind.ANNOTATE_ATTR:
            raw = child.displayname or child.spelling
            if raw:
                out.append(raw)
    return out


def qualified_cpp_name(cursor: cindex.Cursor) -> str:
    parts = [cursor.spelling]
    cur = cursor.semantic_parent
    while cur is not None and cur.kind != cindex.CursorKind.TRANSLATION_UNIT:
        if cur.kind in {
            cindex.CursorKind.NAMESPACE,
            cindex.CursorKind.STRUCT_DECL,
            cindex.CursorKind.CLASS_DECL,
            cindex.CursorKind.CLASS_TEMPLATE,
        } and cur.spelling:
            parts.append(cur.spelling)
        cur = cur.semantic_parent
    return "::".join(reversed(parts))


def parse_model(cursor: cindex.Cursor, include_unannotated: bool) -> ModelDef | None:
    annotations = cursor_annotations(cursor)

    table = ""
    table_annotated = False
    for ann in annotations:
        if ann.startswith(ANNOTATE_PREFIX_TABLE):
            table = ann[len(ANNOTATE_PREFIX_TABLE) :]
            table_annotated = True
            break
    if not table:
        table = snake_case(cursor.spelling)

    fields: list[FieldDef] = []
    any_field_annotated = False
    for child in cursor.get_children():
        if child.kind != cindex.CursorKind.FIELD_DECL or not child.spelling:
            continue
        column = child.spelling
        primary_key = False
        annotated = False
        for ann in cursor_annotations(child):
            if ann == "pk":
                primary_key = True
                annotated = True
            elif ann.startswith(ANNOTATE_PREFIX_COLUMN):
                column = ann[len(ANNOTATE_PREFIX_COLUMN) :]
                annotated = True
        any_field_annotated = any_field_annotated or annotated
        fields.append(
            FieldDef(
                member=child.spelling,
                column=column,
                primary_key=primary_key,
                annotated=annotated,
            )
        )

    if not fields:
        return None
    if not include_unannotated and not table_annotated and not any_field_annotated:
        return None

    return ModelDef(
        cpp_type=qualified_cpp_name(cursor),
        local_name=cursor.spelling,
        table=table,
        fields=fields,
    )


def collect_models(
    tu: cindex.TranslationUnit,
    target_files: set[pathlib.Path],
    include_unannotated: bool,
) -> list[ModelDef]:
    out: list[ModelDef] = []
    seen: set[str] = set()

    def visit(cursor: cindex.Cursor) -> None:
        if cursor.kind in {
            cindex.CursorKind.STRUCT_DECL,
            cindex.CursorKind.CLASS_DECL,
        } and cursor.is_definition() and cursor.spelling:
            loc_file = cursor.location.file
            if loc_file is not None:
                loc_path = pathlib.Path(str(loc_file)).resolve()
                if loc_path in target_files:
                    key = cursor.get_usr() or qualified_cpp_name(cursor)
                    if key not in seen:
                        seen.add(key)
                        model = parse_model(cursor, include_unannotated)
                        if model is not None:
                            out.append(model)

        for child in cursor.get_children():
            visit(child)

    visit(tu.cursor)
    return out


def render(models: list[ModelDef], namespace_name: str) -> str:
    lines: list[str] = []
    lines.append("// Generated by scripts/sql_orm_codegen.py. Do not edit manually.")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cstdint>")
    lines.append("#include <string>")
    lines.append("#include <string_view>")
    lines.append("#include <type_traits>")
    lines.append("#include <utility>")
    lines.append("#include <vector>")
    lines.append("")
    lines.append('#include "corouv/sql/orm.h"')
    lines.append("")
    lines.append(f"namespace {namespace_name} {{")
    lines.append("")
    lines.append("namespace detail {")
    lines.append("template <class T>")
    lines.append("inline corouv::sql::Value to_sql_value(T&& value) {")
    lines.append("    using U = std::remove_cv_t<std::remove_reference_t<T>>;")
    lines.append("    if constexpr (std::is_same_v<U, bool>) {")
    lines.append("        return corouv::sql::Value(static_cast<bool>(value));")
    lines.append("    }")
    lines.append("    if constexpr (std::is_integral_v<U> && !std::is_same_v<U, bool>) {")
    lines.append("        return corouv::sql::Value(static_cast<std::int64_t>(value));")
    lines.append("    }")
    lines.append("    if constexpr (std::is_floating_point_v<U>) {")
    lines.append("        return corouv::sql::Value(static_cast<double>(value));")
    lines.append("    }")
    lines.append("    return corouv::sql::Value(std::forward<T>(value));")
    lines.append("}")
    lines.append("}  // namespace detail")
    lines.append("")

    for model in models:
        orm_name = model.local_name + "Orm"
        pk_field = next((f for f in model.fields if f.primary_key), None)
        set_fields = [f for f in model.fields if not f.primary_key]
        if not set_fields:
            set_fields = list(model.fields)

        lines.append(f"struct {orm_name} {{")
        lines.append(f"    using Model = {model.cpp_type};")
        lines.append(
            f'    static constexpr std::string_view table = "{escape_cpp_string(model.table)}";'
        )
        if pk_field is not None:
            lines.append(
                f'    static constexpr std::string_view primary_key = "{escape_cpp_string(pk_field.column)}";'
            )
        lines.append("")
        lines.append("    static corouv::sql::orm::TableMetaRuntime table_meta() {")
        lines.append("        corouv::sql::orm::TableMetaRuntime meta;")
        lines.append("        meta.table = std::string(table);")
        lines.append(f"        meta.columns.reserve({len(model.fields)});")
        for field in model.fields:
            lines.append(
                f'        meta.columns.push_back("{escape_cpp_string(field.column)}");'
            )
        if pk_field is not None:
            lines.append(
                f'        meta.primary_key = std::string("{escape_cpp_string(pk_field.column)}");'
            )
        lines.append("        return meta;")
        lines.append("    }")
        lines.append("")
        lines.append("    static corouv::sql::Params params_from_model(const Model& model) {")
        lines.append("        corouv::sql::Params params;")
        lines.append(f"        params.reserve({len(model.fields)});")
        for field in model.fields:
            lines.append(
                f"        params.push_back(detail::to_sql_value(model.{field.member}));"
            )
        lines.append("        return params;")
        lines.append("    }")
        lines.append("")
        lines.append(
            "    static corouv::Task<corouv::sql::Result> find_all("
            "corouv::sql::Connection& conn, std::string where = {}, "
            "corouv::sql::Params params = {}) {"
        )
        lines.append(
            "        co_return co_await corouv::sql::orm::find_all("
            "conn, table_meta(), std::move(where), std::move(params));"
        )
        lines.append("    }")
        lines.append("")
        lines.append(
            "    static corouv::Task<corouv::sql::Result> select("
            "corouv::sql::Connection& conn, "
            "corouv::sql::orm::SelectOptions options = {}) {"
        )
        lines.append(
            "        co_return co_await corouv::sql::orm::select("
            "conn, table_meta(), std::move(options));"
        )
        lines.append("    }")
        lines.append("")
        if pk_field is not None:
            lines.append(
                "    static corouv::Task<corouv::sql::Result> find_by_pk("
                "corouv::sql::Connection& conn, corouv::sql::Value pk_value) {"
            )
            lines.append(
                "        co_return co_await corouv::sql::orm::find_by_pk("
                "conn, table_meta(), std::move(pk_value));"
            )
            lines.append("    }")
            lines.append("")

        lines.append(
            "    static corouv::Task<std::int64_t> insert("
            "corouv::sql::Connection& conn, corouv::sql::Params values) {"
        )
        lines.append(
            "        co_return co_await corouv::sql::orm::insert("
            "conn, table_meta(), std::move(values));"
        )
        lines.append("    }")
        lines.append("")
        lines.append(
            "    static corouv::Task<std::int64_t> insert_model("
            "corouv::sql::Connection& conn, const Model& model) {"
        )
        lines.append(
            "        co_return co_await insert(conn, params_from_model(model));"
        )
        lines.append("    }")
        lines.append("")

        if pk_field is not None:
            lines.append(
                "    static corouv::sql::Params set_params_from_model("
                "const Model& model) {"
            )
            lines.append("        corouv::sql::Params params;")
            lines.append(f"        params.reserve({len(set_fields)});")
            for field in set_fields:
                lines.append(
                    f"        params.push_back(detail::to_sql_value(model.{field.member}));"
                )
            lines.append("        return params;")
            lines.append("    }")
            lines.append("")
            lines.append(
                "    static corouv::Task<std::int64_t> update_by_pk("
                "corouv::sql::Connection& conn, corouv::sql::Params values, "
                "corouv::sql::Value pk_value) {"
            )
            lines.append("        std::vector<std::string> set_columns;")
            lines.append(f"        set_columns.reserve({len(set_fields)});")
            for field in set_fields:
                lines.append(
                    f'        set_columns.push_back("{escape_cpp_string(field.column)}");'
                )
            lines.append(
                "        co_return co_await corouv::sql::orm::update_by_pk("
                "conn, table_meta(), set_columns, std::move(values), "
                "std::move(pk_value));"
            )
            lines.append("    }")
            lines.append("")
            lines.append(
                "    static corouv::Task<std::int64_t> update_model("
                "corouv::sql::Connection& conn, const Model& model) {"
            )
            lines.append(
                f"        auto pk = detail::to_sql_value(model.{pk_field.member});"
            )
            lines.append(
                "        co_return co_await update_by_pk("
                "conn, set_params_from_model(model), std::move(pk));"
            )
            lines.append("    }")
            lines.append("")
            lines.append(
                "    static corouv::Task<std::int64_t> delete_by_pk("
                "corouv::sql::Connection& conn, corouv::sql::Value pk_value) {"
            )
            lines.append(
                "        co_return co_await corouv::sql::orm::delete_by_pk("
                "conn, table_meta(), std::move(pk_value));"
            )
            lines.append("    }")
            lines.append("")

        lines.append(
            "    static corouv::Task<corouv::sql::Result> join("
            "corouv::sql::Connection& conn, "
            "const std::vector<corouv::sql::orm::JoinSpec>& joins, "
            "std::string where = {}, corouv::sql::Params params = {}, "
            "std::string select_expr = {}) {"
        )
        lines.append(
            "        co_return co_await corouv::sql::orm::join_query("
            "conn, table_meta(), joins, std::move(where), std::move(params), "
            "std::move(select_expr));"
        )
        lines.append("    }")
        lines.append("")
        lines.append(
            "    static corouv::Task<corouv::sql::Result> join_with_options("
            "corouv::sql::Connection& conn, "
            "const std::vector<corouv::sql::orm::JoinSpec>& joins, "
            "corouv::sql::orm::SelectOptions options = {}) {"
        )
        lines.append(
            "        co_return co_await corouv::sql::orm::join_query("
            "conn, table_meta(), joins, std::move(options));"
        )
        lines.append("    }")
        lines.append("")
        lines.append(
            "    static corouv::Task<corouv::sql::Result> one_to_one("
            "corouv::sql::Connection& conn, "
            "const corouv::sql::orm::OneToOneRelation& relation, "
            "corouv::sql::orm::SelectOptions options = {}, "
            "std::string base_ref = {}) {"
        )
        lines.append(
            "        co_return co_await corouv::sql::orm::join_one_to_one("
            "conn, table_meta(), relation, std::move(options), "
            "std::move(base_ref));"
        )
        lines.append("    }")
        lines.append("")
        lines.append(
            "    static corouv::Task<corouv::sql::Result> one_to_many("
            "corouv::sql::Connection& conn, "
            "const corouv::sql::orm::OneToManyRelation& relation, "
            "corouv::sql::orm::SelectOptions options = {}, "
            "std::string base_ref = {}) {"
        )
        lines.append(
            "        co_return co_await corouv::sql::orm::join_one_to_many("
            "conn, table_meta(), relation, std::move(options), "
            "std::move(base_ref));"
        )
        lines.append("    }")
        lines.append("")
        lines.append(
            "    static corouv::Task<corouv::sql::Result> many_to_many("
            "corouv::sql::Connection& conn, "
            "const corouv::sql::orm::ManyToManyRelation& relation, "
            "corouv::sql::orm::SelectOptions options = {}, "
            "std::string base_ref = {}) {"
        )
        lines.append(
            "        co_return co_await corouv::sql::orm::join_many_to_many("
            "conn, table_meta(), relation, std::move(options), "
            "std::move(base_ref));"
        )
        lines.append("    }")
        lines.append("};")
        lines.append("")

    lines.append(f"}}  // namespace {namespace_name}")
    lines.append("")
    return "\n".join(lines)


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate lightweight ORM wrappers from SQL annotations."
    )
    parser.add_argument("--input", "-i", action="append", required=True)
    parser.add_argument("--output", "-o", required=True)
    parser.add_argument("--clang-arg", action="append", default=[])
    parser.add_argument("--std", default="c++20")
    parser.add_argument("--libclang")
    parser.add_argument("--namespace", default="corouv::sql::generated")
    parser.add_argument("--include-unannotated", action="store_true")
    parser.add_argument("--no-force-clang-annotate", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)

    cindex.Config.set_compatibility_check(False)
    if args.libclang:
        cindex.Config.set_library_file(args.libclang)

    input_files = [pathlib.Path(p).resolve() for p in args.input]
    for file_path in input_files:
        if not file_path.exists():
            raise SystemExit(f"error: input file not found: {file_path}")

    clang_args = ["-x", "c++", f"-std={args.std}", *args.clang_arg]
    if not args.no_force_clang_annotate:
        clang_args.append("-DCOROUV_SQL_FORCE_CLANG_ANNOTATE=1")

    index = cindex.Index.create()
    all_models: list[ModelDef] = []
    for path in input_files:
        tu = index.parse(str(path), args=clang_args)
        hard_errors = [
            d for d in tu.diagnostics if d.severity >= cindex.Diagnostic.Error
        ]
        if hard_errors:
            details = "\n".join(str(d) for d in hard_errors)
            raise SystemExit(
                f"error: failed to parse {path} with libclang:\n{details}"
            )
        all_models.extend(
            collect_models(
                tu=tu,
                target_files={path},
                include_unannotated=args.include_unannotated,
            )
        )

    dedup: dict[str, ModelDef] = {}
    for model in all_models:
        dedup.setdefault(model.cpp_type, model)
    models = list(dedup.values())
    models.sort(key=lambda m: m.cpp_type)

    rendered = render(models, args.namespace)
    out_path = pathlib.Path(args.output).resolve()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
